services:
  dtsidecar:
    image: localhost/oneagent-codemodules:${DT_IMAGE_TAG}
    healthcheck:
      test: "curl -f http://localhost:8080/readiness"
      interval: 5s
      timeout: 5s
      retries: 10
    user: 0:0
    volumes:
      - sharedvolume:/shared/
  appcontainer:
    image: "mcr.microsoft.com/dotnet/samples:aspnetapp"
    depends_on:
      dtsidecar: 
        condition: service_healthy 
    ports:
      - "8080"
    volumes:
      - sharedvolume:/shared/
    environment:
      - LD_PRELOAD=/shared/dynatrace/oneagent/agent/lib64/liboneagentproc.so
      - DT_AGENTACTIVE=${DT_AGENTACTIVE}   
      - DT_LOGSTREAM=${DT_LOGSTREAM}   
      - DT_LOGLEVELCON=${DT_LOGLEVELCON}   
      - DT_TENANT=${DT_TENANT}
      - DT_TENANTTOKEN=${DT_TENANTTOKEN}
      - DT_CONNECTION_POINT=${DT_CONNECTION_POINT}
volumes:
  sharedvolume:
    driver:
      local