ARG DT_BASEIMG

FROM golang:1.25-alpine AS build

WORKDIR /src

ADD go.mod .
ADD keepalive ./keepalive
ADD healthprobe ./healthprobe
ADD serverless-bootstrap.go .

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

RUN go test ./keepalive -v
RUN go test ./healthprobe -v
RUN go build -o /bin/serverless-bootstrap ./serverless-bootstrap.go

FROM ${DT_BASEIMG} AS dtbase

FROM curlimages/curl
COPY --from=dtbase /opt/dynatrace /opt/dynatrace

COPY --from=build /bin/serverless-bootstrap /opt/serverless-bootstrap

EXPOSE 8080
ENTRYPOINT ["/opt/serverless-bootstrap","--keepalive","--healthprobe", "/opt/dynatrace/oneagent/agent/lib64/dynatrace-bootstrapper","--source=/opt/dynatrace/oneagent","--target=/shared/dynatrace/oneagent", "--debug"]   