ARG DT_BASEIMG

FROM golang:1.21 AS build
WORKDIR /src

ADD go.mod .
ADD keepalive  ./keepalive
ADD copy_dir.go .

RUN go test ./keepalive -v
RUN go build -o /bin/copy_dir ./copy_dir.go

FROM ${DT_BASEIMG} AS dtbase

FROM scratch
COPY --from=dtbase /opt/dynatrace /opt/dynatrace
COPY --from=build /bin/copy_dir /bin/copy_dir

ENTRYPOINT ["/bin/copy_dir","/opt/dynatrace","/home/dynatrace","keepalive"]
